# Generated by Django 5.0.7 on 2024-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("friend_id", models.IntegerField()),
                ("requested", models.BooleanField(default=True)),
                ("validated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
