# Generated by Django 5.0.7 on 2024-07-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0002_alter_friend_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="v1.user"
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
